<a href="https://colab.research.google.com/github/selfor21/NN-FROM-SCRATCH-LOW-LEVEL/blob/main/C_02_Coding_Neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## 05/12/2023 - ZIP FUNCTION!


In [ ]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

In [ ]:
#ZIP FUNCTION - WHAT FOR?

for t in zip(weights, biases):
  print(t)

([0.2, 0.8, -0.5, 1], 2)
([0.5, -0.91, 0.26, -0.5], 3)
([-0.26, -0.27, 0.17, 0.87], 0.5)


In [ ]:
outputs = []
for neuron_weights, neuron_bias in zip(weights, biases):
  # Zeroed output of given neuron
  neuron_output = 0
  for input, weight in zip(neuron_weights, inputs):
    neuron_output += input * weight
  neuron_output += neuron_bias

  outputs.append(neuron_output)

outputs


[4.8, 1.21, 2.385]

## 06/12/2023 - 38 - Dot Product and Vector Addiction


### Cross Product results a Vector. Dot Product results a scalar.

### Single Neuron
















In [ ]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0


In [ ]:
outputs = np.dot(inputs,weights) + bias
outputs

4.8

### Multiple Neuron

In [2]:
inputs  = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]
layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


## 10/12/2023 - 54 - A Batch of Data

### A Batch of Input´s

In [4]:
inputs = [ [1.0, 2.0, 3.0,  2.5],
           [2.0, 5.0, -1.0, 2.0],
           [-1.5, 2.7, 3.3, -0.8]]
weights= [[ 0.2,   0.8 , -0.5,  1.0],
          [ 0.5,  -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]


### inputs = matrix [3x4] and weights = matrix [3x4] - necessary to transpose weights.

In [5]:
outputs = np.dot(inputs, np.array(weights).T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
