<a href="https://colab.research.google.com/github/selfor21/NN-FROM-SCRATCH-LOW-LEVEL/blob/main/UC_04_Activation_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
'''In general, neural network will have two types of activation functions.
The first will be the function used in hidden layers
Second will be used in the output layer.
Usually the function used for hidden neurons will be the same for all of them.'''

'In general, neural network will have two types of activation functions.\nThe first will be the function used in hidden layers\nSecond will be used in the output layer.\nUsually the function used for hidden neurons will be the same for all of them.'

## The Activation Function

In [1]:
# The Step Activation Function
# The Linear Activation Function
# The Sigmoid Activation Function
# The Rectified Linear Activation Function


In [7]:
pip install nnfs

In [8]:
import numpy as np
import nnfs
nnfs.init()

In [9]:
import matplotlib.pyplot as plt
from nnfs.datasets import spiral_data

In [10]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
      self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
      self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
      self.output = np.dot(inputs, self.weights) + self.biases


## ReLU Activation Function

In [14]:
class Activation_ReLU:
  # Forward Pass
  def forward(self, inputs):
    self.output = np.maximum(0,inputs)


In [12]:
# Create dataset
X, y = spiral_data(samples=100, classes=3)


In [22]:
# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)
# Create ReLU activation (to be used with Dense layer):
activation1 = Activation_ReLU()
# Make a forward pass of our training data through this layer
dense1.forward(X)


In [25]:
print(np.round(dense1.output[:5],4))

[[ 0.e+00  0.e+00  0.e+00]
 [-0.e+00 -1.e-04  0.e+00]
 [-1.e-04 -2.e-04 -0.e+00]
 [-2.e-04 -4.e-04 -1.e-04]
 [-3.e-04 -5.e-04 -2.e-04]]


In [27]:
# Forward pass through activation func.
# Takes in output from previous layer
activation1.forward(dense1.output)
print(np.round(activation1.output[:5],8))

[[0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 1.91e-06]
 [0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00]]


## Softmax Activation Function